### ISSUE TITLE
About the sample rate

### ISSUE THREAD

**Issue by QiuyueXue** [pedvide/ADC#15]
Hello, sorry to bother you but I have  a problem now to set the sample rate. I learned from your documentation that I can change the sample rate by  adc->setSamplingSpeed(SPEED), and the speed can be ADC_VERY_LOW_SPEED, ADC_LOW_SPEED, ADC_MED_SPEED, ADC_HIGH_SPEED or ADC_VERY_HIGH_SPEED, but I want to know the exact sample rate for the further algorithm, and I don't need a very high sample rate(441000 is enough).

 I found that the sample rate is not stable when I use adc->setSamplingSpeed(SPEED), for example I got about 272000 data for two seconds, and got 460650 data for four seconds when I set the same sample rate.

So what should I do if I want an accurate sample rate? How to set it? Sorry to bother you, thanks a lot!

**Comment by palmerr23** [comment]
Hi,

Better to use the teensy forums for this kind of discussion: https://forum.pjrc.com/

Short answer is to use a clock on the teensy to trigger single (or synchronised) conversions.

Richard
