### ISSUE TITLE
Bug in void ADC_Module::stopContinuous()?

### ISSUE THREAD

**Issue by kukks1** [pedvide/ADC#35]
Hello,
nice work. :-)
 
Line 1127 ff:
    // decrease the counter of measurements (unless it's 0)
    if(!num_measurements) {
        num_measurements--;
    }

I guess, it should read:
    if(num_measurements) {
  
Best wishes, kukks1

**Comment by pedvide** [comment]
Fixed, in branch teensy4, will merge soon.
Thanks and sorry for the delay!
