### ISSUE TITLE
RingBufferDMA Channel 2 on ADC_0 Fails to Update Second Half

### ISSUE THREAD

**Issue by cversek** [pedvide/ADC#4]
Just want to mention that this library has been super useful so far, but I am running into a weird issue with trying to use DMA on the Teensy 3.1 with code that is very similar to your example but uses ```startSynchronizedSingleRead``` for pins A9 and A3.  It appears that the last 4 samples in the size 8 ring buffer do not get updated on only ADC_0, whereas ADC_1 seems to work correctly. I will post some code below that hopefully will recreate the error for you.

**Comment by pedvide** [comment]
Hello, I've pushed an update to the RingBufferDMA class and examples.
It doesn't work in Teensy LC yet, but now it uses Paul's DMAChannel, so it should be more portable and compatible with other libraries that use DMA.
The update is not final, as I'd like to hide the buffer definition from the user, but for the moment that's what I have.
