### ISSUE TITLE
ADC speed with Teensy 3.1

### ISSUE THREAD

**Issue by hirschmensch** [pedvide/ADC#5]
This isn't really an issue but more of a question.
I am having a bit of a hard time understanding how fast the sampling speed can go.
"ADC_HIGH_SPEED is guaranteed to be the highest possible speed within specs for resolutions less than 16 bits (lower or eq than 18 MHz)."
So in this setting the Teensy 3.1 can go up tp 18MHz?
Well why does the AnalogContinuousRead example then say:
"At 96 Mhz (bus at 48 MHz), 632 KHz is the fastest we can do within the specs, and only if the sample's impedance is low enough."
I don't get it. :)

**Comment by pedvide** [comment]
Please see this post and the following answers:
https://forum.pjrc.com/threads/25532-ADC-library-update-now-with-support-for-Teensy-3-1?p=67538&viewfull=1#post67538

**Comment by hirschmensch** [comment]
thank you!
