### ISSUE TITLE
Teensy coverage for ADC A14-A17

### ISSUE THREAD

**Issue by eagleman1022** [pedvide/ADC#60]
Whenever possible, could we get coverage for Teensy 4.1 ADC A14 thru A17?

**Comment by pedvide** [comment]
I have worked a bit in supporting Teensy 4.1, hopefully this weekend I'll finish it.

**Comment by pedvide** [comment]
See #58

**Comment by pedvide** [comment]
@eagleman1022 I don't have a Teensy 4.1 yet with me, can you test the latest version of this library? It should work.

**Comment by pedvide** [comment]
#61 adds support for pins A14-A17
