### ISSUE TITLE
Spontaneous ADC failure

### ISSUE THREAD

**Issue by benkrasnow** [pedvide/ADC#65]
Has anyone ever experienced a spontaneous permanent failure of the ADC on the K60 line of MCUs?  There is a thread on the NXP forum (https://community.nxp.com/thread/381051) , and I have recently encountered this same very strange problem with the Teensy 3.6 using this ADC library.  I apologize that my question is not directly related to this library, but I'm hoping someone has heard of this or has an idea of what could possibly cause it.

**Comment by pedvide** [comment]
I've never seen anything like that, but I don't run a Teensy continuously. In the datassheet there's a limit to the speed the ADC can run, if you use higher speeds maybe that can be a problem? I don't think I can help you, sorrry!
