### ISSUE TITLE
undefined reference to `AnalogBufferDMA::init(ADC*, signed char)' in PlatformIO Release

### ISSUE THREAD

**Issue by Ic-ks** [pedvide/ADC#71]
The current Teensy_ADC PlatformIO library version (8.0.38) throws an error when compiling the `adc_dma` example:

`undefined reference to AnalogBufferDMA::init(ADC*, signed char) `

 I noticed that this error is already fixed in the master branch (`#ifdef ADC_USE_DMA` must be moved below the includes in `AnalogBufferDMA.h` and `AnalogBufferDMA.cpp`). 
Would it be possible to release a new PlatformIO library with this fix included?

**Comment by pedvide** [comment]
Thanks for the bug report, I have published a new version on platformio. Please let me know if it works!

**Comment by Ic-ks** [comment]
Nice! Version: 
![image](https://user-images.githubusercontent.com/29521057/104442837-ebd49e00-5595-11eb-9858-8f42a80125a1.png) works like a charm. Thank you very much!
