### ISSUE TITLE
Protect from irq?

### ISSUE THREAD

**Issue by EduardoG26** [pedvide/ADC#8]
Hola Pedro. Great work. I have a suggestion.
Could it be helpful to protect read() against IRQ? I think the case when write() is called from inside an irq is very popular. This may corrupt some variables if colliding with read().
Regards. Eduardo

**Comment by pedvide** [comment]
Sorry for the delay!
I'm not sure what read() function you refer to. Do you mean analogRead()? It's already protected for that. If you call it from an irq and it was already converting, it will stop that conversion, do the irq's conversion and restart the other one when it's done.
