### ISSUE TITLE
Question about ADC on a 3.5 board.

### ISSUE THREAD

**Issue by jimdgit** [pedvide/ADC#87]
Porting from an UNO. vref=default.
I have buttons that set a voltage to ADC0.
UNO VIN=4.6 +5=5.1
5.1 V = 1023
4.1 V = 820 counts

Teensy 3.5 on the tall-dog Due Breakout board vref=ADC_REFERENCE::REF_3V3
3.5. VIN= 5.1 +5=5.1
5.1 V = 1023
4.1 V = 1023
This prevents me from determining which button was pressed.
So how does VIN affect the ADC reading? Or does it?
If it does I will talk to tall-dog about why it is different.

**Comment by Defragster** [comment]
T_3.5 is 5V tolerant, but any voltage over 3.3V is seen as 1023.

Valid scale readings will be seen between 0V and 3.3V

**Comment by jimdgit** [comment]
Can I set the vref to 5V?

**Comment by jimdgit** [comment]
I see ok thanks. I will have to adjust things a bit.

**Comment by pedvide** [comment]
Thanks for answering @Defragster!

**Comment by jimdgit** [comment]
For the record I fixed it with and SMD trim pot glued to the board to scale it to 0-3.3v
